# baseURL
@baseURL = http://localhost:3002

###
# Find All Articles
GET {{ baseURL }}/articles

###
# Find one article
GET {{ baseURL }}/articles/3

###
# Create Article
POST {{ baseURL }}/articles
Content-Type: application/json

{
    "title": "Lorem Ipsum",
	"content": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent finibus arcu et justo bibendum sodales. Aliquam hendrerit scelerisque neque, tristique sodales tortor gravida et. Ut non ipsum a arcu sodales ornare. Sed sed mattis lectus. Curabitur commodo mauris id augue volutpat, congue hendrerit sem ultrices."
}

###
# Delete one article
DELETE {{ baseURL }}/articles/3

###
# Update Article
PATCH  {{ baseURL }}/articles/2
Content-Type: application/json

{
    "title": "testUpdate",
	"content": "testUpdate"
}