# baseURL
@baseURL = http://localhost:3000

###
# Find All Articles
GET {{ baseURL }}/articles

###
# Find one article
GET {{ baseURL }}/articles/1

###
# Create Article
POST {{ baseURL }}/articles
Content-Type: application/json

{
    "title": "test",
	"content": "test"
}