# baseURL
@baseURL = http://localhost:3000

###
# Find All Articles
GET {{ baseURL }}/articles

###
# Find one article
GET {{ baseURL }}/articles/3

###
# Create Article
POST {{ baseURL }}/articles
Content-Type: application/json

{
    "title": "test",
	"content": "test"
}

###
# Delete one article
DELETE {{ baseURL }}/articles/3

###
# Update Article
PATCH  {{ baseURL }}/articles/2
Content-Type: application/json

{
    "title": "testUpdate",
	"content": "testUpdate"
}